version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 8000:8000
    environment:
      PORT: 8000
